language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "8"
  - "9"
  - "10"
env:
  global:
    - CC_TEST_REPORTER_ID=125467a1ee6a975ccd559c38662bdc1dd9540cd2803f98db94e1cf3596738773
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
install:
  - npm install
  - npm install -g jest
script:
  - npm test
