version: 2
checks:
  file-lines:
    config:
      threshold: 600
  method-lines:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 50
plugins:
  eslint:
    enabled: true
  stylelint:
    enabled: true
exclude_patterns:
  - src/locale/**
